### ISSUE TITLE
Передвижение

### ISSUE THREAD

**Issue by ranor2000** [ranor2000/PuzzleGame15#2]
Необходимо реализовать передвижение тайлов

- [x]  реализовать управление клавишами WASD
- [x]  реализовать управление клавишами стрелок
- [x]  определить удобное управление для игрока эксперементальным путем
(например: клавиша вверх это передвижение тайла сверху вниз или снизу вверх?)

**Comment by ranor2000** [comment]
Реализовано управление WASD

**Comment by ranor2000** [comment]
Экспрементальным путём было определено что удобное управление является перемещение пустого квадрата соответсвенно клавишам направления (клавиша вверх - перемещает его вверх и т.д.)

**Comment by Kagary** [comment]
Добавлено перемещение по нажатию стрелочек и символов русского аналога WASD
