### ISSUE TITLE
Победа

### ISSUE THREAD

**Issue by ranor2000** [ranor2000/PuzzleGame15#3]
Неоходимо реализовать конец игры:
- [x] после каждого передвижения проверять соответсвует ли порядок тайлов правильному
- [x] в случае правильного порядка тайлов выводить сообщение о победе

**Comment by ranor2000** [comment]
если порядок правильный, то не имеет значение положение пустого тайла!

**Comment by Kagary** [comment]
Вывод сообщения о победе: выполнено
